# Generated by Django 3.0.5 on 2020-04-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='user',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_email',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_mobile',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_name',
        ),
        migrations.AddField(
            model_name='followers',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
