# Generated by Django 3.0.5 on 2020-04-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200413_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='id',
        ),
        migrations.AddField(
            model_name='followers',
            name='blog_followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.User'),
        ),
    ]
